services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservation/Dockerfile
      target: development
    command: npm run start:dev reservations
    ports:
      - '3001:3000'
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo
